name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.21'

    - name: Build
      run: make build VERSION=${{ env.VERSION }}

    - name: Test
      run: make test # Replace with your actual test command

    - name: Create Packages
      run: |
        make package-deb VERSION=${{ env.VERSION }}
        make package-rpm VERSION=${{ env.VERSION }}
        make package-shar VERSION=${{ env.VERSION }}

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/*.deb
          build/*.rpm
          build/*.shar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
